### ISSUE TITLE
Ad hoc commands/ scripts

### ISSUE THREAD

**Issue by chrism9876** [munkireport/munkireport-php#1554]
Are there any plans to add the ability of being able to run scripts or ad-hoc commands on a or multiple macs. 

I think this would be a great feature. 

But would PHP be able to do something like this. Run in background and report back to webpage?

Ard has become very buggy recently

**Comment by tuxudo** [comment]
There are currently no plans for MunkiReport to run scripts as described on clients. 

For the bugs, make sure you are running the latest release of MunkiReport and the latest release of the modules. If there are still bugs, please file them on the appropriate GitHub repo so that they can be filed and addressed.

**Comment by chrism9876** [comment]
I was thinking a way to implement this would be to store the commands in a table


Table ad-hoc
 Serial
Datetime
Expirarydatetime
command
Command-Id
Result


Then the munkiclient could periodically check a
URL eg Https://munkireport.com/adhoc/serial
Which would return any active commands.

And client could return if successful or not

If I were to work on something like this is it possible it would be merged
