### ISSUE TITLE
Munki Tab to show IP of SoftwareRepoURL (Enhancement)

### ISSUE THREAD

**Issue by WardsParadox** [munkireport/munkireport-php#164]
It would be nice if the Munki Tab view showed the server that the client is using. Would be useful for groups who have multiple servers or environments pointing back to one MunkiReport server.

**Comment by clburlison** [comment]
@WardsParadox, are you still wanting this feature?

1. Do you simply want the output from the munki `SoftwareRepoURL` key to be visible? (easy) 
1. Or want the IP Address because you have multiple servers and you're using a round robin type setup? 

For the latter the only solution that is coming to mind is doing a `ping` or `nslookup` to return the IP address. I kind of dislike this as it's one additional network request...however I can also see the appeal.

**Comment by gmarnin** [comment]
I was thinking SoftwareRepoURL and SoftwareUpdateServerURL (or CatalogURL for 10.11). CatalogURL can be useful if you have multiple servers or more than one branch in the case of Reposado.

**Comment by erikng** [comment]
Check out the munkiinfo PR. It should pull this data.

**Comment by WardsParadox** [comment]
Wow, I never got the notifications for this. Erik's branch that was on Slack is perfect. Thank you both :+1:

**Comment by clburlison** [comment]
This issue can be closed with #400 as it's now in the master branch.
