### ISSUE TITLE
Remote IP Address reported incorrectly

### ISSUE THREAD

**Issue by mrpjdavis** [munkireport/munkireport-php#253]
Just installed Munki and Munkireport and everything seems to work great except the "Remote IP Address" is reported incorrectly.

When looking at the Network Interfaces tab under Ethernet, the IP address is reported correctly:

![screen shot 2015-06-19 at 15 54 33](https://cloud.githubusercontent.com/assets/806125/8256057/31f52dbc-169c-11e5-8023-198866beea59.png)

Not sure if I've done something wrong in the setup? Any help appreciated! 

Thanks

**Comment by bochoven** [comment]
Remote IP address is the address the client uses to connect to the Munkireport server. If there's a proxy in-between, Munkireport will try to get at the originating address.

The addresses listed in the Network tab are the addresses the client uses. Sometimes there is a difference between those due to being behind a NAT or a (reverse) proxy.
