### ISSUE TITLE
Munki Report Pre and Post Flights Time Out

### ISSUE THREAD

**Issue by mohremail** [munkireport/munkireport-php#325]
Since upgrading to server 5.0.4 I've had real issues with munki report... When in the GUI interface of Managed Software Center, I get to preflight tasks, then it times out after 35 seconds... This is what I get in terminal when running managed software update:

bash-3.2$ sudo managedsoftwareupdate
Password:
Managed Software Update Tool
Copyright 2010-2014 The Munki Project
https://github.com/munki/munki

Starting...
    Performing preflight tasks...
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1038, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 637, in main
    result = runScript(preflightscript, 'preflight', runtype)
  File "/usr/local/munki/managedsoftwareupdate", line 185, in runScript
    script, allow_insecure=True, script_args=[runtype])
  File "/usr/local/munki/munkilib/utils.py", line 129, in runExternalScript
    stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
bash-3.2$

**Comment by oleary-bruce** [comment]
IMHO, Server v5.0.4 completely screws a number of services up (that’s a technical description, and my personal experience).

By any chance, did you turn off any services that you normally use prior to installing the server upgrade, such as the Websites service?

Bruce


On Sep 28, 2015, at 1:24 PM, mohremail <notifications@github.com<mailto:notifications@github.com>> wrote:


Since upgrading to server 5.0.4 I've had real issues with munki report... When in the GUI interface of Managed Software Center, I get to preflight tasks, then it times out after 35 seconds... This is what I get in terminal when running managed software update:

bash-3.2$ sudo managedsoftwareupdate
Password:
Managed Software Update Tool
Copyright 2010-2014 The Munki Project
https://github.com/munki/munki

Starting...
Performing preflight tasks...
Traceback (most recent call last):
File "/usr/local/munki/managedsoftwareupdate", line 1038, in
main()
File "/usr/local/munki/managedsoftwareupdate", line 637, in main
result = runScript(preflightscript, 'preflight', runtype)
File "/usr/local/munki/managedsoftwareupdate", line 185, in runScript
script, allow_insecure=True, script_args=[runtype])
File "/usr/local/munki/munkilib/utils.py", line 129, in runExternalScript
stderr=subprocess.PIPE)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
raise child_exception
OSError: [Errno 8] Exec format error
bash-3.2$

**Comment by mohremail** [comment]
No I didn't turn anything off before upgrading.

**Comment by bochoven** [comment]
Did you update the client scripts on the machine you send the output of?

**Comment by bochoven** [comment]
`Exec format error` usually signifies there's something wrong with the script

**Comment by mohremail** [comment]
No I didn't change a thing... only upgraded the server app... thats it. All worked perfect until then... I'm anxious to try it with the latest update to munkireport just released... I hope it fixes it :)

**Comment by mjonesrsn** [comment]
I am having the same issue. I am going back and forth from MunkiReport Version 2.5.3.1368 to beta 6 try to figure out some issues. Server.app 5.0.4
10.11 15A284


Munki works fine then I run the command below

sudo /bin/bash -c "$(curl -s https://myserver.com/munkireport/index.php?/install)”

Get this

Preparing /usr/local/munki/ and /Library/Preferences/MunkiReport
BaseURL is http://myserver.com/munkireport/
Retrieving munkireport scripts
Configuring munkireport
Setting preferences
Installation of MunkiReport v2.5.3 complete.
Running the preflight script for initialization
/usr/local/munki/preflight: line 1: syntax error near unexpected token `newline'
/usr/local/munki/preflight: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'


Munki stops working as I get this issue
Starting...

    Performing preflight tasks...

Traceback (most recent call last):

  File "/usr/local/munki/managedsoftwareupdate", line 1038, in <module>

    main()

  File "/usr/local/munki/managedsoftwareupdate", line 637, in main

    result = runScript(preflightscript, 'preflight', runtype)

  File "/usr/local/munki/managedsoftwareupdate", line 185, in runScript

    script, allow_insecure=True, script_args=[runtype])

  File "/usr/local/munki/munkilib/utils.py", line 129, in runExternalScript

    stderr=subprocess.PIPE)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__

    errread, errwrite)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child

    raise child_exception

OSError: [Errno 8] Exec format error

Resolution

sudo rm -rf /usr/local/munki/

Reinstall Munki

Ran this cmd by accident

bash -c "$(curl https://myserver.com/munkireport/index.php?/install)" bash -i ~/Desktop

Installed pkg. Same issue.

What's weird is I have the same setup in prod and do not experience this issue. Only difference is hardware. MP 2010 vs MM 2014.

**Comment by bochoven** [comment]
You should download the script and evaluate what's wrong with it:

curl https://myserver.com/munkireport/index.php?/install <https://myserver.com/munkireport/index.php?/install)%E2%80%9D> > /tmp/install.sh

chmod +x /tmp/install.sh
/tmp/install.sh

-Arjen

**Comment by mjonesrsn** [comment]
Found the problem, but not the root cause.
-====CHECK OUT THE BaseURL===- 
See the difference. It's missing the s. 

sudo /bin/bash -c "$(curl -s https://myserver.com/munkireport/index.php?/install)"
Preparing /usr/local/munki/ and /Library/Preferences/MunkiReport
BaseURL is http://myserver.researchnow.com/munkireport/
Retrieving munkireport scripts
Configuring munkireport
Setting preferences
Installation of MunkiReport v2.5.3 complete.
Running the preflight script for initialization
/usr/local/munki/preflight: line 1: syntax error near unexpected token `newline'
/usr/local/munki/preflight: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'

Since I have the web server set to redirect http traffic to https. The post and pre flights contained this:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://myserver.com/munkireport//assets/client_installer/postflight">here</a>.</p>
<hr>
<address>Apache Server at myserver.com Port #####</address>
</body></html>

I piped out the script

curl https://myserver.com/munkireport/index.php?/install >> /tmp/install.sh

And show that the BaseURL was http and not https

But why?

That is the magic question. I looked and replaced the httpd.conf and Apache and it still did it. My prod servers are setup the same way and do not have this redirect issue.

**Comment by mjonesrsn** [comment]
Root cause found!

I was looking at my config.php files from prod and dev and comparing. I forgot that I added this to the prod config.php:

	/*
	|===============================================
	| Pass on https forward to $_SERVER['HTTPS'
	|===============================================
	|
	| Apple changed how https traffic is forward
	| in Server.app 5.0.4
	*/
	// Pass on https forward to $_SERVER['HTTPS']
	if(isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
	{
	$_SERVER['HTTPS'] = 'on';
	}

This is in relation to this thread https://groups.google.com/forum/#!topic/munkireport/T6DvbuulKOA

After I added this to the dev config.php:

sudo /bin/bash -c "$(curl -s https://mmyserver.com/munkireport/index.php?/install)"
Password:
Preparing /usr/local/munki/ and /Library/Preferences/MunkiReport
BaseURL is https://myserver.com/munkireport/


BaseURL matched the curl cmd. This was not in the config_default.php in the 2.6 beta1 either.

**Comment by bochoven** [comment]
I added the HTTP_X_FORWARDED_PROTO rule to index.php
