### ISSUE TITLE
munki listing "last seen" column incorrect.

### ISSUE THREAD

**Issue by sphen13** [munkireport/munkireport-php#334]
the "last seen" column on the munki page does not match that of the client listing "check-in"
<img width="1512" alt="screen shot 2015-10-15 at 10 08 53 am" src="https://cloud.githubusercontent.com/assets/524607/10516201/168ef90a-7325-11e5-881d-79e4c800ba03.png">
<img width="960" alt="screen shot 2015-10-15 at 10 08 39 am" src="https://cloud.githubusercontent.com/assets/524607/10516200/168d1428-7325-11e5-8f05-7fc051c4f497.png">

**Comment by aysiu** [comment]
I'm not sure if this is the same issue, but my **Last Seen** is showing sometimes as _in # hours_ instead of just _# hours ago_, and that's messing with the sorting.
<img width="116" alt="screen shot 2016-07-18 at 12 24 32 pm" src="https://cloud.githubusercontent.com/assets/13055957/16928391/36f49a00-4ce7-11e6-9b2d-fc97933105d2.png">
