### ISSUE TITLE
Feature request: iCloud module

### ISSUE THREAD

**Issue by 2mny** [munkireport/munkireport-php#386]
I would like to see an iCloud module that reports the iCloud accounts on a system and the iCloud services enabled. I am currently sending this info to an ARD text field and reading it in munkireport but this is not ideal.

**Comment by clburlison** [comment]
How are you retrieving this information, currently?

**Comment by 2mny** [comment]
Here's my code for writing the data to the ARD text fields. It is simply pulling data from the MobileMe plist in every user account on the computer.
```
#!/usr/bin/env python

import plistlib, os, subprocess
import logging

logging.basicConfig(level=logging.INFO)
txt1 = 'iCloud Inactive'
txt2 = 'Find My Mac: Disabled'

iCloudAccts = []

users = [ dir for dir in os.listdir('/Users/') if os.path.isdir(os.path.join('/Users/', dir))]

for user in users:
	logging.info("Checking user: {}".format(user))
	plist = os.path.join('/Users', user, 'Library/Preferences/MobileMeAccounts.plist')
	logging.info("Checking plist: {}".format(plist))
	if not os.path.isfile(plist):
		logging.info("No Mobile Me plist for: {}".format(user))
		continue
	subprocess.call(['plutil', '-convert', 'xml1', plist])
	pdata = plistlib.readPlist(plist)
	logging.debug("Read plist with data: {}".format(pdata))
	if pdata['Accounts']:
		txt1 = 'iCloud Active: '
		for account in pdata['Accounts']:
			iCloudAccts.append("{} ({})".format(account['AccountID'], account['DisplayName']))
			if [item['Enabled'] for item in account['Services'] if item['Name'] == "FIND_MY_MAC"][0]:
				logging.info("Find my mac IS enabled for {}".format(user))
				txt2 = 'Find My Mac: Enabled'
			else:
				logging.info("Find my mac is NOT enabled for {}".format(user))
	

if iCloudAccts:
	txt1 += str(iCloudAccts)

logging.info("--------Done-------")

subprocess.check_call("defaults write /Library/Preferences/com.apple.RemoteDesktop.plist Text1 -string".split() + [txt1])
subprocess.check_call("defaults write /Library/Preferences/com.apple.RemoteDesktop.plist Text2 -string".split() + [txt2])
```

**Comment by clburlison** [comment]
Alright you've got my interest. I can work on this however it's going to be few days (maybe weeks) before I can get to this. 

Instead of assuming all users are going to be under /Users we should really use 
```bash
/usr/bin/dscl . -list /Users dsAttrTypeStandard:NFSHomeDirectory
```
to get the home directory. That way setups that store user accounts on separate partitions are covered.

@2mny, I have an idea for the client view however **what information are you interested in seeing on the listing view?** 

Currently you are storing all of the "found" icloud accounts in one string however I'd like to split that out. We could do something like the current Network report: so we could have multiple instances of icloud accounts per computers. Sounds good?

**Comment by clburlison** [comment]
The FindMyMac portion of this request is complete with PR #455.
