### ISSUE TITLE
Add path on TimeMachine module

### ISSUE THREAD

**Issue by lolipale** [munkireport/munkireport-php#479]
Hello,
It will be precious to have the destination path of backups on the Time Machine listing.
We use many Time Machine servers.
This field will be a great help.
Have a nice day
Regards

**Comment by poundbangbash** [comment]
The following command will output the pertinent information in xml to be easily parsed.

`tmutil destinationinfo -X`

Can you run that on your machines and confirm it contains the information you're looking for? And can you confirm which key holds that information?

**Comment by poundbangbash** [comment]
I started looking into this and realized it can get complicated as TM can have multiple backup locations.  Are you interested in just the most recent backup location or all?  There is a key 'LastDestination' that would make finding the last location easy.  Parsing thru all possible locations would require some rework of the module methinks.

I started a branch `time-machine` at https://github.com/poundbangbash/munkireport-php/commit/47ed43407615d07a82b8ba9e927b3879c05e4a47

Since this is adding columns to the existing timemachine table I need help figuring out how to dynamically add that.  To test this I just removed the timemachine table.  The fields populate properly but when trying to access the listing on the sever I just get a message that it's loading data and never does.  If anyone wants to fill me in on what I'm doing wrong I'm all eyes.

**Comment by poundbangbash** [comment]
As of commit https://github.com/poundbangbash/munkireport-php/commit/170071bd23c9598e2983e97f6b29d611a4518102 on my fork I have the following:

- Client summary TimeMachine table shows Kind, Name, Location, and # of Destinations 
![screenshot 2016-08-05 22 09 06](https://cloud.githubusercontent.com/assets/1416288/17454390/3de3b6fe-5b59-11e6-8330-0297a8d98700.png)

- Added the same columns to the Listing view 
![screenshot 2016-08-05 22 09 48](https://cloud.githubusercontent.com/assets/1416288/17454396/5805e034-5b59-11e6-8179-cf89c1bda281.png)

- Converted script from .sh to .py for easier parsing of the TM destination info

- Database migration to add the 4 new columns for the new data

I'd appreciate others who could test this branch as well as my Time Machine environment is simple and only consists of my home network volume (and a 2nd local drive I hooked up as a 2nd destination on to get multiple destinations susses out).

Before testing this you should backup your database as there is a database migration on the timemachine table.  

To test using git:

```
`cd` into your munkireport-php directory
git remote add eholtam https://github.com/poundbangbash/munkireport-php
git fetch eholtam
git checkout eholtam/time-machine
git pull eholtam time-machine
```

Clients will need to have the new timemachine.py script installed.  If you currently have the timemachine set to install, run the following on the client:
`sudo /bin/bash -c "$(curl -s http://example.server.com/index.php?/install)"`
That will uninstall the timemachine.sh, install timemachine.py, and start a preflight run.  Once the preflight is done run `sudo /usr/local/munki/postflight` to send the data to the server.

**Comment by bochoven** [comment]
So you're recording only one destination?

**Comment by poundbangbash** [comment]
At the moment yes. I can see how knowing all locations would be beneficial, not just the last used one is. I'm not sure how to injest multiple destinations for one computer though. Any insight on how to do that would be appreciated.

**Comment by bochoven** [comment]
You'll need to drop the UNIQUE restriction for serial_number, so you can record multiple locations per machine.

**Comment by bochoven** [comment]
Maybe you could open a Pull Request so we can discuss the details there.

**Comment by poundbangbash** [comment]
PR sent

**Comment by tuxudo** [comment]
This was added with PR #650
