### ISSUE TITLE
Computer images broken on Location Report

### ISSUE THREAD

**Issue by kevinmcox** [munkireport/munkireport-php#910]
I imagine this is the same issue as seen previously on the client details page (but I can't find the issue to reference).

Images for the pinpoint pop-up on the map in the Location Report all display as missing images:

![model image](https://user-images.githubusercontent.com/25358601/33629346-59d25dbc-d9c9-11e7-86ad-f9fe304542c4.png)

**Comment by jelockwood** [comment]
The problem is due to the images being accessed via km.support.apple.com.edgekey.net but that site using a SSL certificate which is only valid for *.test.edgekey.net and hence not being valid for that location. Either a different certificate would have to be used, or the images moves to a different location which matches the current certificate.

**Comment by kevinmcox** [comment]
I remember a fix being needed for the same problem on the client details page but didn't find an issue here with the specific details.
